go_import_path: github.com/barklyprotects/cert-manager

jobs:
  include:
    - stage: test
      dist: trusty
      language: go
      go: 1.9
      env:
      - KUBERNETES_VERSION=v1.7.0
      before_script:
      # Install CLI dependencies
      - curl -Lo helm.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-v2.6.1-linux-amd64.tar.gz && tar xvf helm.tar.gz && sudo mv linux-amd64/helm /usr/local/bin
      - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBERNETES_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.24.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      # Install nsenter
      - docker run -v /usr/local/bin:/hostbin munnerz/ubuntu-nsenter cp /nsenter /hostbin/nsenter
      script:
      - ./hack/test/setup-minikube.sh
      - ./hack/ci.sh
    - stage: test
      dist: trusty
      language: go
      go: 1.9
      script:
      - make verify verify_pr test
